name: MacPilot
options:
  bundleIdPrefix: com.raulriera
  deploymentTarget:
    macOS: "26.0"
  xcodeVersion: "26.0"
  minimumXcodeGenVersion: "2.42.0"

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
    MACOSX_DEPLOYMENT_TARGET: "26.0"

targets:
  MacPilot:
    type: application
    platform: macOS
    sources:
      - MacPilot
    dependencies:
      - target: MacPilotMCP
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.raulriera.MacPilot
        INFOPLIST_FILE: MacPilot/Info.plist
        CODE_SIGN_ENTITLEMENTS: MacPilot/MacPilot.entitlements
        GENERATE_INFOPLIST_FILE: false
        PRODUCT_NAME: MacPilot
        SWIFT_EMIT_LOC_STRINGS: "YES"
        ENABLE_HARDENED_RUNTIME: "YES"
        CODE_SIGN_IDENTITY: "-"
    postCompileScripts:
      - name: "Embed MacPilotMCP"
        script: |
          cp "${BUILT_PRODUCTS_DIR}/MacPilotMCP" "${BUILT_PRODUCTS_DIR}/MacPilot.app/Contents/MacOS/MacPilotMCP"
        basedOnDependencyAnalysis: false

  MacPilotMCP:
    type: tool
    platform: macOS
    sources:
      - MacPilotMCP
      - path: MacPilot/Features/Tools/Tool.swift
      - path: MacPilot/Features/Tools/ClipboardTool.swift
      - path: MacPilot/Features/Tools/NotificationTool.swift
      - path: MacPilot/Features/Tools/WebTool.swift
      - path: MacPilot/Features/Tools/ToolRegistry.swift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.raulriera.MacPilotMCP
        GENERATE_INFOPLIST_FILE: true
        PRODUCT_NAME: MacPilotMCP

  MacPilotTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - MacPilotTests
      - path: MacPilotMCP/JSONRPCServer.swift
    dependencies:
      - target: MacPilot
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.raulriera.MacPilotTests
        GENERATE_INFOPLIST_FILE: true
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/MacPilot.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/MacPilot"
        BUNDLE_LOADER: "$(TEST_HOST)"
