#!/bin/sh
# No additional env vars — operates on the MacPilot repo itself
. "$(dirname "$0")/../lib/macpilot.sh"

cd "$MACPILOT_DIR" || exit 1

TODAY="$(date +%Y%m%d)"
BRANCH="improve/$TODAY"
WORKTREE="$MACPILOT_DIR/.worktrees/$BRANCH"

# Clean up worktree on exit
cleanup_worktree() {
  if [ -d "$WORKTREE" ]; then
    git worktree remove --force "$WORKTREE" 2>/dev/null || true
  fi
  git branch -D "$BRANCH" 2>/dev/null || true
}

# Create an isolated worktree so main is never touched
git branch -D "$BRANCH" 2>/dev/null || true
mkdir -p "$(dirname "$WORKTREE")"
git worktree add -b "$BRANCH" "$WORKTREE" HEAD 2>/dev/null || {
  echo "Failed to create worktree" >&2
  notify "MacPilot: $AGENT_NAME" "Failed to create worktree." "high"
  exit 1
}

cd "$WORKTREE" || exit 1

run_agent "You are the MacPilot meta-agent. Your job is to improve MacPilot itself.
You are working in a git worktree at $WORKTREE. All file paths are relative to this directory.

Step 1 — Gather context (read these concurrently where possible):
  a) Read config/goals.md for user-directed improvement goals.
  b) Read the 5 most recent .log files in logs/ (use: ls -t logs/*.log 2>/dev/null | head -5, then read each).
     Look for: failures, timeouts, wasted turns, repeated errors.
  c) Read the 5 most recent reports in reports/ (use: ls -t reports/*.md 2>/dev/null | head -5, then read each).
     Look for: recurring themes, patterns the agents miss, quality issues.
  d) Read all agent scripts in agents/ and plists in plists/ to understand current capabilities.

Step 2 — Based on goals and observations, make improvements. You may:
  - Edit existing agent scripts (better prompts, tuned parameters)
  - Create new agent scripts following the pattern in existing agents
  - Create new plist files following the pattern in existing plists (use __MACPILOT_DIR__ and __HOME__ placeholders)
  - Edit lib/macpilot.sh if a shared improvement is needed
  - Do NOT edit config/.env or config/goals.md

Step 3 — Write a summary report to reports/improve-$TODAY.md with:
  - Date and what you analyzed
  - Each change you made: file path, what changed, and why
  - Any goals from goals.md you addressed
  - Suggestions you chose not to implement and why

IMPORTANT: After writing the report file, stop immediately. Do not verify, re-read, or do any follow-up work." \
  --max-turns 40 \
  --timeout 900 \
  --quiet \
  --allowedTools "Read Edit Write Bash Glob Grep"

# Commit any changes the agent made in the worktree
if [ -n "$(git -C "$WORKTREE" status --porcelain 2>/dev/null)" ]; then
  git -C "$WORKTREE" add -A
  git -C "$WORKTREE" commit -m "improve: automated improvements ($TODAY)

Generated by the MacPilot improve agent.
See reports/improve-$TODAY.md for details."

  # Copy report to main repo's reports dir so it's visible without switching branches
  if [ -f "$WORKTREE/reports/improve-$TODAY.md" ]; then
    cp "$WORKTREE/reports/improve-$TODAY.md" "$MACPILOT_DIR/reports/"
  fi

  cd "$MACPILOT_DIR"
  change_count="$(git diff --stat main.."$BRANCH" | tail -1)"
  notify "MacPilot: $AGENT_NAME" "Improvements proposed on branch $BRANCH ($change_count)"
else
  # Copy report even if no code changes were made
  if [ -f "$WORKTREE/reports/improve-$TODAY.md" ]; then
    cp "$WORKTREE/reports/improve-$TODAY.md" "$MACPILOT_DIR/reports/"
  fi

  cd "$MACPILOT_DIR"
  cleanup_worktree
  notify "MacPilot: $AGENT_NAME" "No changes proposed. See reports/improve-$TODAY.md"
fi
