#!/bin/sh
. "$(dirname "$0")/../lib/macpilot.sh"

cd "$MACPILOT_DIR" || exit 1

TODAY="$(date +%Y%m%d)"
BRANCH="improve/$TODAY"

# Create a branch for the agent's changes
git checkout -b "$BRANCH" 2>/dev/null || {
  echo "Branch $BRANCH already exists, reusing it" >&2
  git checkout "$BRANCH" 2>/dev/null || exit 1
}

run_agent "You are the MacPilot meta-agent. Your job is to improve MacPilot itself.

Step 1 — Read config/goals.md for user-directed improvement goals.

Step 2 — Read the 5 most recent .log files in logs/ (use: ls -t logs/*.log | head -5, then read each).
  Look for: failures, timeouts, wasted turns, repeated errors.

Step 3 — Read the 5 most recent reports in reports/ (use: ls -t reports/*.md | head -5, then read each).
  Look for: recurring themes, patterns the agents miss, quality issues.

Step 4 — Read all agent scripts in agents/ and plists in plists/ to understand current capabilities.

Step 5 — Based on goals and observations, make improvements. You may:
  - Edit existing agent scripts (better prompts, tuned parameters)
  - Create new agent scripts following the pattern in existing agents
  - Create new plist files following the pattern in existing plists (use __MACPILOT_DIR__ and __HOME__ placeholders)
  - Edit lib/macpilot.sh if a shared improvement is needed
  - Do NOT edit config/.env or config/goals.md

Step 6 — Write a summary report to reports/improve-$TODAY.md with:
  - Date and what you analyzed
  - Each change you made: file path, what changed, and why
  - Any goals from goals.md you addressed
  - Suggestions you chose not to implement and why

IMPORTANT: After writing the report file, stop immediately. Do not verify, re-read, or do any follow-up work." \
  --max-turns 20 \
  --timeout 600 \
  --allowedTools "Read Edit Write Bash Glob Grep"

# Commit any changes the agent made
if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
  git add -A
  git commit -m "improve: automated improvements ($TODAY)

Generated by the MacPilot improve agent.
See reports/improve-$TODAY.md for details."

  change_count="$(git diff --stat main.."$BRANCH" | tail -1)"
  notify "MacPilot: $AGENT_NAME" "Improvements proposed on branch $BRANCH ($change_count)"
else
  notify "MacPilot: $AGENT_NAME" "No changes proposed. See reports/improve-$TODAY.md"
fi
